name: Check Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    name: Check Ubuntu Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: sudo apt install libcurl4-openssl-dev && sudo apt remove libdeflate-dev -y

    - name: Check build
      run: mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=../ && make && make install

    - name: Install Check
      run: ./bin/biscuit version

    # These haven't been generated yet, so uncomment when ready
    # - name: Run tests
    #   run: make check

  build-mac:
    name: Check macOS Build

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check build
      run: mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=../ && make && make install

    - name: Install Check
      run: ./bin/biscuit version

    # These haven't been generated yet, so uncomment when ready
    # - name: Run tests
    #   run: make check
